// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addOrUpdateInventoryItemStmt, err = db.PrepareContext(ctx, addOrUpdateInventoryItem); err != nil {
		return nil, fmt.Errorf("error preparing query AddOrUpdateInventoryItem: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.getAllUsersStmt, err = db.PrepareContext(ctx, getAllUsers); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllUsers: %w", err)
	}
	if q.getUserByIDStmt, err = db.PrepareContext(ctx, getUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByID: %w", err)
	}
	if q.getUserByUsernameStmt, err = db.PrepareContext(ctx, getUserByUsername); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByUsername: %w", err)
	}
	if q.getUserInventoryStmt, err = db.PrepareContext(ctx, getUserInventory); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserInventory: %w", err)
	}
	if q.getUserInventoryItemStmt, err = db.PrepareContext(ctx, getUserInventoryItem); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserInventoryItem: %w", err)
	}
	if q.updateInventoryItemStmt, err = db.PrepareContext(ctx, updateInventoryItem); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateInventoryItem: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addOrUpdateInventoryItemStmt != nil {
		if cerr := q.addOrUpdateInventoryItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addOrUpdateInventoryItemStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.getAllUsersStmt != nil {
		if cerr := q.getAllUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllUsersStmt: %w", cerr)
		}
	}
	if q.getUserByIDStmt != nil {
		if cerr := q.getUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDStmt: %w", cerr)
		}
	}
	if q.getUserByUsernameStmt != nil {
		if cerr := q.getUserByUsernameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByUsernameStmt: %w", cerr)
		}
	}
	if q.getUserInventoryStmt != nil {
		if cerr := q.getUserInventoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserInventoryStmt: %w", cerr)
		}
	}
	if q.getUserInventoryItemStmt != nil {
		if cerr := q.getUserInventoryItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserInventoryItemStmt: %w", cerr)
		}
	}
	if q.updateInventoryItemStmt != nil {
		if cerr := q.updateInventoryItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateInventoryItemStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                           DBTX
	tx                           *sql.Tx
	addOrUpdateInventoryItemStmt *sql.Stmt
	createUserStmt               *sql.Stmt
	getAllUsersStmt              *sql.Stmt
	getUserByIDStmt              *sql.Stmt
	getUserByUsernameStmt        *sql.Stmt
	getUserInventoryStmt         *sql.Stmt
	getUserInventoryItemStmt     *sql.Stmt
	updateInventoryItemStmt      *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                           tx,
		tx:                           tx,
		addOrUpdateInventoryItemStmt: q.addOrUpdateInventoryItemStmt,
		createUserStmt:               q.createUserStmt,
		getAllUsersStmt:              q.getAllUsersStmt,
		getUserByIDStmt:              q.getUserByIDStmt,
		getUserByUsernameStmt:        q.getUserByUsernameStmt,
		getUserInventoryStmt:         q.getUserInventoryStmt,
		getUserInventoryItemStmt:     q.getUserInventoryItemStmt,
		updateInventoryItemStmt:      q.updateInventoryItemStmt,
	}
}
