// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Move struct {
	MoveID   int16  `json:"moveId"`
	Name     string `json:"name"`
	Power    int16  `json:"power"`
	Accuracy int16  `json:"accuracy"`
}

type PokemonSpecy struct {
	SpeciesID   int16  `json:"speciesId"`
	Name        string `json:"name"`
	BaseAttack  int16  `json:"baseAttack"`
	BaseDefense int16  `json:"baseDefense"`
	BaseSpeed   int16  `json:"baseSpeed"`
}

type User struct {
	UserID       int64     `json:"userId"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"passwordHash"`
	CreatedAt    time.Time `json:"createdAt"`
}

type UserInventory struct {
	UserID   int64  `json:"userId"`
	Item     string `json:"item"`
	Quantity int32  `json:"quantity"`
}

type UserPokemon struct {
	UpID       int64          `json:"upId"`
	UserID     int64          `json:"userId"`
	SpeciesID  int16          `json:"speciesId"`
	Nickname   sql.NullString `json:"nickname"`
	Level      int16          `json:"level"`
	Xp         int32          `json:"xp"`
	AttackMod  int16          `json:"attackMod"`
	DefenseMod int16          `json:"defenseMod"`
	SpeedMod   int16          `json:"speedMod"`
}
