// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	GetAllUsers(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
