// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"context"
)

type Querier interface {
	AddOrUpdateInventoryItem(ctx context.Context, arg AddOrUpdateInventoryItemParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetUserByID(ctx context.Context, userID int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserInventory(ctx context.Context, userID int64) ([]UserInventory, error)
	GetUserInventoryItem(ctx context.Context, arg GetUserInventoryItemParams) (UserInventory, error)
	UpdateInventoryItem(ctx context.Context, arg UpdateInventoryItemParams) error
}

var _ Querier = (*Queries)(nil)
