// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user.sql

package database

import (
	"context"
)

const addOrUpdateInventoryItem = `-- name: AddOrUpdateInventoryItem :exec
INSERT INTO user_inventory (user_id, item, quantity)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, item) DO UPDATE SET
  quantity = quantity + $3
`

type AddOrUpdateInventoryItemParams struct {
	UserID   int64  `json:"userId"`
	Item     string `json:"item"`
	Quantity int32  `json:"quantity"`
}

func (q *Queries) AddOrUpdateInventoryItem(ctx context.Context, arg AddOrUpdateInventoryItemParams) error {
	_, err := q.exec(ctx, q.addOrUpdateInventoryItemStmt, addOrUpdateInventoryItem, arg.UserID, arg.Item, arg.Quantity)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash)
VALUES ($1, $2, $3)
RETURNING user_id, username, email, password_hash, created_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"passwordHash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser, arg.Username, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT user_id, username, email, password_hash, created_at FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.query(ctx, q.getAllUsersStmt, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, username, email, password_hash, created_at FROM users
WHERE user_id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, userID int64) (User, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT user_id, username, email, password_hash, created_at FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.queryRow(ctx, q.getUserByUsernameStmt, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserInventory = `-- name: GetUserInventory :many
SELECT user_id, item, quantity FROM user_inventory
WHERE user_id = $1
`

func (q *Queries) GetUserInventory(ctx context.Context, userID int64) ([]UserInventory, error) {
	rows, err := q.query(ctx, q.getUserInventoryStmt, getUserInventory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserInventory
	for rows.Next() {
		var i UserInventory
		if err := rows.Scan(&i.UserID, &i.Item, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserInventoryItem = `-- name: GetUserInventoryItem :one
SELECT user_id, item, quantity FROM user_inventory
WHERE user_id = $1 AND item = $2
`

type GetUserInventoryItemParams struct {
	UserID int64  `json:"userId"`
	Item   string `json:"item"`
}

func (q *Queries) GetUserInventoryItem(ctx context.Context, arg GetUserInventoryItemParams) (UserInventory, error) {
	row := q.queryRow(ctx, q.getUserInventoryItemStmt, getUserInventoryItem, arg.UserID, arg.Item)
	var i UserInventory
	err := row.Scan(&i.UserID, &i.Item, &i.Quantity)
	return i, err
}

const updateInventoryItem = `-- name: UpdateInventoryItem :exec
UPDATE user_inventory
SET quantity = $3
WHERE user_id = $1 AND item = $2
`

type UpdateInventoryItemParams struct {
	UserID   int64  `json:"userId"`
	Item     string `json:"item"`
	Quantity int32  `json:"quantity"`
}

func (q *Queries) UpdateInventoryItem(ctx context.Context, arg UpdateInventoryItemParams) error {
	_, err := q.exec(ctx, q.updateInventoryItemStmt, updateInventoryItem, arg.UserID, arg.Item, arg.Quantity)
	return err
}
